// Mocks generated by Mockito 5.4.4 from annotations
// in islamic/test/presentation/home/cubit/beranda_material_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:annibros/data/repository/material_content_repository.dart'
    as _i2;
import 'package:annibros/domain/models/material/material_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MaterialContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMaterialContentRepository extends _i1.Mock
    implements _i2.MaterialContentRepository {
  MockMaterialContentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MaterialModel>> getAllMaterials() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMaterials, []),
            returnValue: _i3.Future<List<_i4.MaterialModel>>.value(
              <_i4.MaterialModel>[],
            ),
          )
          as _i3.Future<List<_i4.MaterialModel>>);

  @override
  _i3.Future<List<_i4.MaterialModel>> getMaterialsByCategory(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMaterialsByCategory, [category]),
            returnValue: _i3.Future<List<_i4.MaterialModel>>.value(
              <_i4.MaterialModel>[],
            ),
          )
          as _i3.Future<List<_i4.MaterialModel>>);

  @override
  _i3.Future<_i4.MaterialModel?> getMaterialById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMaterialById, [id]),
            returnValue: _i3.Future<_i4.MaterialModel?>.value(),
          )
          as _i3.Future<_i4.MaterialModel?>);

  @override
  _i3.Future<List<_i4.MaterialModel>> searchMaterials(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMaterials, [query]),
            returnValue: _i3.Future<List<_i4.MaterialModel>>.value(
              <_i4.MaterialModel>[],
            ),
          )
          as _i3.Future<List<_i4.MaterialModel>>);

  @override
  _i3.Future<void> updateLastRead(String? materialId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastRead, [materialId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleBookmark(String? materialId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBookmark, [materialId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.MaterialModel>> getBookmarkedMaterials() =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkedMaterials, []),
            returnValue: _i3.Future<List<_i4.MaterialModel>>.value(
              <_i4.MaterialModel>[],
            ),
          )
          as _i3.Future<List<_i4.MaterialModel>>);

  @override
  _i3.Future<_i4.MaterialModel?> getLastReadMaterial() =>
      (super.noSuchMethod(
            Invocation.method(#getLastReadMaterial, []),
            returnValue: _i3.Future<_i4.MaterialModel?>.value(),
          )
          as _i3.Future<_i4.MaterialModel?>);

  @override
  _i3.Future<bool> isBookmarked(String? materialId) =>
      (super.noSuchMethod(
            Invocation.method(#isBookmarked, [materialId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
